#!/usr/bin/env python
# Copyright (C) 2016. BMW Car IT GmbH. All rights reserved.
"""DLT file analyser"""
import sys

from dltlyse.run_dltlyse import main


if __name__ == "__main__":
    sys.exit(main())
