name: dltlyse-ci-actions

on: [push, pull_request]

jobs:
  run-test-for-dltlyse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LIBDLT_VERSION:
          - "v2.18.8"
    steps:
      - uses: actions/checkout@v3
      - name: Build dltlyse unit test docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          build-args: |
             LIBDLT_VERSION=${{ matrix.LIBDLT_VERSION }}
          tags: dltlyse/dltlyse-unittest:${{ matrix.LIBDLT_VERSION }}
      - name: Run tox static check
        uses: addnab/docker-run-action@v3
        with:
          image: dltlyse/dltlyse-unittest:${{ matrix.LIBDLT_VERSION }}
          options: -v ${{ github.workspace }}:/dltlyse -w /dltlyse
          run: tox -e statictest
      - name: Run tox
        uses: addnab/docker-run-action@v3
        with:
          image: dltlyse/dltlyse-unittest:${{ matrix.LIBDLT_VERSION }}
          options: -v ${{ github.workspace }}:/dltlyse -w /dltlyse
          run: tox
